### ISSUE TITLE
As an Admin, I should be able to specify a home city for driver assignment.

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/food-bank-app#15]

**Comment by yzhbankov** [comment]
Hi, i just forked this project and start it locally. I have some questions.
- how it is possible to add the driver?
- this issue is about the additional field in DB? (could you tell me more information about issue?)
Thanks.

**Comment by DealPete** [comment]
This project was adapted from a application used internally by the Canadian food bank Chadei Kaduri. The Google Maps plugin is currently hard-coded to display their location is Toronto by default. You can see this by doing a search for "geoToronto".
We want to change this so that the admin user can set the address of his own food bank as the default location. I suspect the easiest way to do this would be to have an address field in "App Settings", and have the driver module use that value.

If you're wondering how to set a volunteer as a "driver", go to the volunteers tab, click "view" on a user, and select the "Driver" button along the bottom of the info page.

**Comment by yzhbankov** [comment]
After entering the city name in the App Settings the Google Maps should rebuild the map to the said city in the Route Assignment menu?
